version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID = os.getenv('ACCESS_KEY')
      - AWS_SECRET_ACCESS_KEY = os.getenv('SECRET_KEY')
      - AWS_BUCKET_NAME = os.getenv('BUCKET_NAME')
      - AWS_BUCKET_URL = os.getenv('BUCKET_URL')
